### ISSUE TITLE
SSDP.Client.start Error

### ISSUE THREAD

**Issue by tielur** [NationalAssociationOfRealtors/ssdp#1]
I'm attempting to get this running, I've followed the readme and did the following:
1. git clone https://github.com/NationalAssociationOfRealtors/ssdp.git
2. mix do deps.get, deps.compile
3. iex -S mix
4. SSDP.Client.start

When I run `SSDP.Client.start` I get the following error:

```elixir
iex(1)> SSDP.Client.start
** (exit) exited in: GenServer.call(SSDP.Client, :start, 5000)
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, :eaddrinuse}
            (ssdp) lib/ssdp/client.ex:57: SSDP.Client.handle_call/3
            (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:774: GenServer.call/3
iex(1)> 
09:44:18.049 [error] GenServer SSDP.Client terminating
** (MatchError) no match of right hand side value: {:error, :eaddrinuse}
    (ssdp) lib/ssdp/client.ex:57: SSDP.Client.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.183.0>): :start
State: %SSDP.Client.State{devices: [], handlers: [], port: 1900, udp: nil}
Client #PID<0.183.0> is alive
    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:771: GenServer.call/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:239: :elixir.eval_forms/4
    (iex) lib/iex/evaluator.ex:219: IEx.Evaluator.handle_eval/5
    (iex) lib/iex/evaluator.ex:200: IEx.Evaluator.do_eval/3
    (iex) lib/iex/evaluator.ex:178: IEx.Evaluator.eval/3
    (iex) lib/iex/evaluator.ex:77: IEx.Evaluator.loop/1
```

**Comment by tielur** [comment]
This may have been caused by messing around another UPnP library, I did a full restart and now this is working. Maybe we want to add error handling to catch this issues?

**Comment by entone** [comment]
It's saying that address is already in use, you must have had another SSDP
server running. It should fail as it did.
